### ISSUE TITLE
Configuration

### ISSUE THREAD

**Issue by poroszd** [samebug/samebug-eclipse-plugin#3]
The plugin will have a remote server to communicate with, so we want to have a UI for the server configuration.
Create an extension so that the plugin will have a config menu displayed under the eclipse preferences (on Linux it is 'Window > Preferences'), and have a form with a few fields like:
- server url (URL)
- api key (String)
- connection timeout (Integer)

Also, for testing purposes create an action that displays the current values of the settings.

**Comment by vesakr** [comment]
Finished the UI for the configuration page. Need to implement the actual functionality of it.
