### ISSUE TITLE
Login screen

### ISSUE THREAD

**Issue by poroszd** [samebug/samebug-eclipse-plugin#4]
The plugin will need to identify the user before it can start communicating with the server. For this I'd like to have a tool window with a simple login/registration screen that gets displayed when eclipse is started. 

I attach two snapshots how the login and sign up screen looks like.
About the exact behavior and functionality of the login screen, we will specify it later.
![signup-screen](https://user-images.githubusercontent.com/6347894/28107463-31ffaa78-66e8-11e7-91a2-337dee8ca64a.png)
![login-screen](https://user-images.githubusercontent.com/6347894/28107464-3202f246-66e8-11e7-930c-fc7ab6ab36c0.png)

**Comment by vesakr** [comment]
One idea is to have the login open in Eclipse's own browser. Otherwise it has to be done using SWT and it will not look very nice. The browser saves us a lot of time in designing and will end up looking better.
